server:
  port: 9090

spring:
  application:
    name: Usersdummy

  datasource:
    url: jdbc:mysql://localhost:3306/DummyUsers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
    open-in-view: false

dummy-users:
  database:
    bootstrap-url: jdbc:mysql://localhost:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    name: DummyUsers
